export const ngoData = [
  {
    id: 1,
    title: "Disha – Early Intervention & School Readiness ",
    summary: [
      "Day care facility for children with NT disabilities in the age group of 0-10 years for at least 4-6 hours per day for a batch size 20",
      "Training and counseling to children and the parents to enable mainstreaming of children ",
      "Professional services by special educators, therapists and counselors ",

      "Availability of optional transport facility",
      "Continuous evaluation of children and mapping of development chart·",
      "Assistance and guidance for admission to schools·",
      "KPIs monitored shall be – PwD strength, LIG:Non LIG ratio, PwD development, PwD mainstreaming, Parent Counselling",
    ],
    img: "images/NGOs/ngo1.jpg",
  },
  {
    id: 2,
    title: "Vikaas - Day Care ",
    summary: [
      "Day care facility for children with NT disabilities in the age group of 0-10 years for at least 4-6 hours per day for a batch size 20",
      "Training and counseling to children and the parents to enable mainstreaming of children ",
      "Professional services by special educators, therapists and counselors ",

      "Availability of optional transport facility",
      "Continuous evaluation of children and mapping of development chart·",
      "Assistance and guidance for admission to schools·",
      "KPIs monitored shall be – PwD strength, LIG:Non LIG ratio, PwD development, PwD mainstreaming, Parent Counselling",
    ],
    img: "images/NGOs/ngo2.jpg",
  },
  {
    id: 3,
    title: "Samarth – Respite Care Residential Scheme",
    summary: [
      "Residential facilities including meals for orphans/abandoned, families in crises, destitute, BPL and LIG PwDs in all age groups for a batch size 30.",
      " Provision to shift an adult resident to GHARAUNDA if stay in Samarth exceeds 5 years and PwD is an adult·",
      "Professional services by special educators, therapists and counsellors for age-specific vocational and pre-vocational activities·",
      "RO should own the location or its should be on a lease of minimum 5 years with renewable clause·",
      "KPIs monitored shall be – PwD strength, LIG:Non LIG ratio, PwD registration with Niramaya scheme, PwD development, Gainful employment of PwD, Inclusion events organized",
    ],
    img: "images/NGOs/ngo3.jpeg",
  },
  {
    id: 4,
    title: "GHARAUNDA – Group Home for Adults",
    summary: [
      "Residential facilities including meals and all other facilities for life long stay of adult PwDs (>18 years of age) for a batch size 20.",
      "Professional services by special educators, therapists and counsellors for age-specificvocational and pre-vocational activities·",
      "RO should own the location or its should be on a lease of minimum 10 years with renewable clause·",
      "Provision of crisis fund per Gharaunda Centre to be maintained with the National Trust – INR 10,00,000/-",
      "KPIs monitored shall be – PwD strength, LIG:Non LIG ratio, PwD registration with Niramaya scheme, PwD development, Gainful employment of PwD, Inclusion events organized",
    ],
    img: "images/NGOs/ngo4.jpeg",
  },
  {
    id: 5,
    title: "Niramaya – Health Insurance",
    summary: [
      "Health Insurance for PwDs under NTAct·",
      "Full premium to be paid by the National Trust·",
      "Benefits include surgery, hospitalization, OPD, medicines, dentistry, medical tests, therapies etc. up to Rs.1 Lakh·",
      "No requirement of health check-up or age proof·",
      "No bar for government or private hospitals/practitioners·",
      "Enrollment on monthly basis through Registered Organizations (RO)·",
      " Facilitation through 34 regional claim centers.",
      "Annual enrolment fee for BPL Rs. 250/-, Non BPL Rs. 500/- and PwD with Legal Guardian (Other than natural parents) FREE.",
      "KPIs monitored shall be: turnaround time for the application, Niramaya status report",
    ],
    img: "images/NGOs/ngo5.jpeg",
  },
  {
    id: 6,
    title: "Gyan Prabha – Education Support ",
    summary: [
      "Encourage PwDs to pursue vocational training/higher education/ professional courses.",
      "Wide range of courses like medical, engineering, law, management and regular graduation and post graduation covered·",
      "No age or income limit for eligibility·",
      "Recurring fixed amount for the specified courses covering course fees, transportation, books,OPEs (max 10%) etc. on presenting proofs except OPE·",
      "Funding shall be provided for maximum duration of course or till when course is completed by PwD as applicable·",
      "KPIs monitored shall be: turnaround time for the application, Gyan Prabha status report",
    ],
    img: "images/NGOs/ngo3.jpeg",
  },
  {
    id: 7,
    title: "Sahyogi – Care Associate Training",
    summary: [
      "Creating a pool of skilled care associates through theoretical and on-the-job training to support PwDs and their families·",
      "Two types of courses – Primary (3 months), Advanced (6 months) having both theory and internship·",
      "Parents and guardians are also eligible to apply for the courses. However, they shall not be involved in internship period of course·",
      "Meeting(s) for placement amongst families, institutions and trained care associates on a quarterly basis·",
      "KPIs monitored shall be – trainee strength, trainee attendance, internship opportunities,placement, RO visit status report",
    ],
    img: "images/NGOs/ngo4.jpeg",
  },
  {
    id: 8,
    title: "Prerna – Marketing Assistance",
    summary: [
      "Funding for participation in fairs and/or exhibitions at district, state, regional and national level·",
      "NTto sponsor up to four events in a financial year·",
      "Minimum participation of 51% PwDs in production of saleable items/articles·",
      "An incentive of 10% for RO on sales turnover verified by Office of DC/DM/LLC/Social Welfare·",
      "NT shall also reimburse the expenses that ROs incurred in designing and publishing brochures marketing the products prepared by PwDs·",
      "KPIs monitored shall be: Event participation and Growth rate of PwD supported",
    ],
    img: "images/NGOs/ngo2.jpg",
  },
  {
    id: 9,
    title: "Sambhav – Aids and Assistive Devices",
    summary: [
      "Additional centres to be set up in cities of India with population of more than 5 million (as per 2011 Census)·",
      "Demonstration of aids, assistive devices, software & an accessible model of Kitchen, Living Room & Bathroom etc. for enabling and empowering the PwDs·",
      "Management coordinator at these Sambhav centres shall be deployed by NT·",
      "ROs to provide one demonstrator/facilitator and one maintenance staff·",
      "Sambhav centre can procure new aids/ assistive devices and same shall be reimbursed by NT within maximum limit allowed·",
      "KPIs monitored shall be: increased no. of visitors, organizing visits to the centre (for ROs,educational institute and Medical institute) ",
    ],
    img: "images/NGOs/ngo1.jpg",
  },
  {
    id: 10,
    title: "Badhte Kadam – Awareness & Community ",
    summary: [
      "Awareness generation for general public and community stakeholders through various activities for example exhibition, rallies, workshops, media outreach etc.",
      "Innovative/special proposals to be sanctioned separately·",
      "Create platforms for collaborative initiatives between govt. officials, medical fraternity, legal professionals & educational institutes for the betterment of PwDs·",
      "Outreach activities in areas where NTis under represented·",
      "Maximize benefits of NTschemes·",
      "KPIs monitored shall be: activities completed, enabling changes in society and gathering feedback",
    ],
    img: "images/NGOs/ngo5.jpeg",
  },
];
